#!/bin/bash

# Copy the shipped defaults into an existing user's home.
#
# /etc/skel only fires when a user is created. The ISO gets that order right:
# omarchy-settings lands first, then the user is created and inherits it. This
# fork installs onto a machine that is already running, where the user existed
# long before Omarchy did, so seeding /etc/skel alone reaches nobody.
#
# The symptom is not subtle but it is misleading: Hyprland starts, writes its
# own autogenerated config, and comes up as a bare compositor. No bar, no
# keybindings, no Omarchy environment -- and nothing in any log says why,
# because nothing failed.
#
# omarchy-provision-user deliberately does not do this; it handles only what
# skel cannot express. omarchy-reinstall-configs does, but it also refreshes
# limine and the Neovim setup, neither of which exists here.
#
# Unlike the ISO, this runs on a machine that may already be in use, so
# anything replaced is backed up first.
#
# Honours OMARCHY_ARM_DRY_RUN=1.

omarchy_arm_seed_home() {
  local dry="${OMARCHY_ARM_DRY_RUN:-0}"
  local skel="${OMARCHY_ARM_SKEL:-/etc/skel}"
  local home="${1:-$HOME}"
  local seeded=0 replaced=0 rel dest

  [[ -d $skel ]] || return 0

  while IFS= read -r -d '' file; do
    rel="${file#"$skel"/}"

    # Backups this installer made in the template are not defaults.
    [[ $rel == *.omarchy-arm.bak ]] && continue

    dest="$home/$rel"

    if [[ -e $dest ]]; then
      replaced=$((replaced + 1))
      if (( ! dry )); then
        [[ -e $dest.omarchy-arm.bak ]] || cp -a "$dest" "$dest.omarchy-arm.bak"
      fi
    fi

    seeded=$((seeded + 1))
    if (( ! dry )); then
      mkdir -p "$(dirname "$dest")"
      cp -a "$file" "$dest"
    fi
  done < <(find "$skel" -type f -print0 | sort -z)

  if (( dry )); then
    echo "[dry-run] would copy $seeded shipped defaults into $home ($replaced would be replaced, each backed up)"
  else
    echo "Copied $seeded shipped defaults into $home ($replaced replaced, each backed up as *.omarchy-arm.bak)."
  fi
}
